require 'active_support/core_ext'
require 'active_record'
require 'active_record-readonly_model'
require 'active_record-enumerated_model/version'
require 'active_record-enumerated_model/enumerated_model'
